import "./globals.css";
import{ SessionProvider }from 'next-auth/react';
import { Toaster } from "@/components/ui/sonner"
import { Kanit } from "next/font/google"; // Import the Kanit font from next/font/google
import type { Metadata } from "next";
import { Providers } from "@/components/stateMangement/store/provider";
import { ThemeProvider } from "next-themes";

const kanit = Kanit({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "MAGE",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full overflow-x-hidden">
      <body className={`h-full  ${kanit.className}`}>
      <SessionProvider>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <Providers>

        {children}
        </Providers>
        <Toaster />
        </ThemeProvider>
      </SessionProvider>
  
      </body>
    </html>
  )
}